### ISSUE TITLE
call to readUInt32LE results in RangeError for empty buffer

### ISSUE THREAD

**Issue by leroix** [bmavity/ges-client#34]
While writing a lot of data to eventstore, I experienced a range error here:

https://github.com/bmavity/ges-client/blob/master/tcp/lengthPrefixMessageFramer.js#L54

Should we account for empty buffers or is an empty buffer a sign of a deeper issue?

**Comment by leroix** [comment]
Here's the full stacktrace

```
buffer.js:582
    throw new RangeError('Trying to access beyond buffer length');
    ^
RangeError: Trying to access beyond buffer length
    at checkOffset (buffer.js:582:11)
    at Buffer.readUInt32LE (buffer.js:642:5)
    at Object.getContentLength (/Users/leroix/deepthought/node_modules/ges-client/tcp/lengthPrefixMessageFramer.js:54:16)
    at MessageReceiver.processData (/Users/leroix/deepthought/node_modules/ges-client/tcp/messageReceiver.js:25:30)
    at MessageReceiver._handleMultiplePackets (/Users/leroix/deepthought/node_modules/ges-client/tcp/messageReceiver.js:58:8)
    at MessageReceiver.processData (/Users/leroix/deepthought/node_modules/ges-client/tcp/messageReceiver.js:31:9)
    at MessageReceiver._handleMultiplePackets (/Users/leroix/deepthought/node_modules/ges-client/tcp/messageReceiver.js:58:8)
    at MessageReceiver.processData (/Users/leroix/deepthought/node_modules/ges-client/tcp/messageReceiver.js:31:9)
    at MessageReceiver._handleMultiplePackets (/Users/leroix/deepthought/node_modules/ges-client/tcp/messageReceiver.js:58:8)
    at MessageReceiver.processData (/Users/leroix/deepthought/node_modules/ges-client/tcp/messageReceiver.js:31:9)
    at MessageReceiver._handleMultiplePackets (/Users/leroix/deepthought/node_modules/ges-client/tcp/messageReceiver.js:58:8)
    at MessageReceiver.processData (/Users/leroix/deepthought/node_modules/ges-client/tcp/messageReceiver.js:31:9)
    at MessageReceiver._handleMultiplePackets (/Users/leroix/deepthought/node_modules/ges-client/tcp/messageReceiver.js:58:8)
    at MessageReceiver.processData (/Users/leroix/deepthought/node_modules/ges-client/tcp/messageReceiver.js:31:9)
    at MessageReceiver._handleMultiplePackets (/Users/leroix/deepthought/node_modules/ges-client/tcp/messageReceiver.js:58:8)
    at MessageReceiver.processData (/Users/leroix/deepthought/node_modules/ges-client/tcp/messageReceiver.js:31:9)
    at MessageReceiver._handleMultiplePackets (/Users/leroix/deepthought/node_modules/ges-client/tcp/messageReceiver.js:58:8)
    at MessageReceiver.processData (/Users/leroix/deepthought/node_modules/ges-client/tcp/messageReceiver.js:31:9)
```

**Comment by bmavity** [comment]
Whoops, I just saw this. It got buried in a flood of io.js messages. I will check into it in the next day or two.

**Comment by bmavity** [comment]
Question: Which version of the server are you using which method are you using on the connection? After looking at the stack trace closer, it seems to error when reading the content length of a message from the server, but I do not think that should ever happen so there must be some issue with the multiple packet handling code. I will see if I can reproduce.

**Comment by leroix** [comment]
I was using v3.0.1 of the server, and I was using appendToStream to do 1000s of writes in a very short time.

**Comment by bmavity** [comment]
Any possibility you could put the code up in a gist so I can reproduce?

**Comment by leroix** [comment]
I actually deleted it like a dummy. It was just a tiny wrapper around the client that takes lines from stdin and uses appendToStream to save them to eventstore.

Something like

```
var stream = process.stdin.pipe(split())

stream.on('data', ....)
```

Split can be found [here](https://www.npmjs.com/package/split). It just splits stdin lines by '\n'.

**Comment by bmavity** [comment]
Ok. Will take a look at some point this week. Hopefully my schedule will
clear up a bit.

**Comment by gregoryyoung** [comment]
I;d be interested in seeing a curl outout from the call having issues.

There is another thread going about null events and embed=content. I have
not yet been able to reproduce the issue where content is not delivered in
the atom feed but would not be surprised if there is some edge case it can
happen in

On Mon, Jan 19, 2015 at 7:40 PM, Brian Mavity <notifications@github.com>
wrote:

> Ok. Will take a look at some point this week. Hopefully my schedule will
> clear up a bit.
>
> On Mon, Jan 19, 2015 at 11:23 AM, leroix <notifications@github.com>
> wrote:
>
> > I actually deleted it like a dummy. It was just a tiny wrapper around
> the
> > client that takes lines from stdin and uses appendToStream to save them
> to
> > eventstore.
> >
> > Something like
> >
> > var stream = process.stdin.pipe(split())
> >
> > stream.on('data', ....)
> >
> > Split can be found here <https://www.npmjs.com/package/split>. It just
> > splits stdin lines by '\n'.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/bmavity/ges-client/issues/34#issuecomment-70529980>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bmavity/ges-client/issues/34#issuecomment-70532461>.
>



-- 
Studying for the Turing test

**Comment by bmavity** [comment]
The client is tcp only for now. Are you asking me to do a curl that matches
what the tcp client is doing? Sorry if I am confused about something
obvious. :)

**Comment by gregoryyoung** [comment]
oh sorry I was thinking it was over atom.

In that case just the protobuf exchange works :)

On Mon, Jan 19, 2015 at 11:16 PM, Brian Mavity <notifications@github.com>
wrote:

> The client is tcp only for now. Are you asking me to do a curl that
> matches
> what the tcp client is doing? Sorry if I am confused about something
> obvious. :)
>
> On Mon, Jan 19, 2015 at 1:49 PM, Greg Young <notifications@github.com>
> wrote:
>
> > I;d be interested in seeing a curl outout from the call having issues.
> >
> > There is another thread going about null events and embed=content. I
> have
> > not yet been able to reproduce the issue where content is not delivered
> in
> > the atom feed but would not be surprised if there is some edge case it
> can
> > happen in
> >
> > On Mon, Jan 19, 2015 at 7:40 PM, Brian Mavity <notifications@github.com>
>
> > wrote:
> >
> > > Ok. Will take a look at some point this week. Hopefully my schedule
> will
> > > clear up a bit.
> > >
> > > On Mon, Jan 19, 2015 at 11:23 AM, leroix <notifications@github.com>
> > > wrote:
> > >
> > > > I actually deleted it like a dummy. It was just a tiny wrapper
> around
> > > the
> > > > client that takes lines from stdin and uses appendToStream to save
> > them
> > > to
> > > > eventstore.
> > > >
> > > > Something like
> > > >
> > > > var stream = process.stdin.pipe(split())
> > > >
> > > > stream.on('data', ....)
> > > >
> > > > Split can be found here <https://www.npmjs.com/package/split>. It
> > just
> > > > splits stdin lines by '\n'.
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <https://github.com/bmavity/ges-client/issues/34#issuecomment-
> 70529980>.
> >
> > >
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/bmavity/ges-client/issues/34#issuecomment-70532461>.
>
> >
> > >
> >
> >
> >
> > --
> > Studying for the Turing test
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/bmavity/ges-client/issues/34#issuecomment-70550209>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bmavity/ges-client/issues/34#issuecomment-70562299>.
>



-- 
Studying for the Turing test

**Comment by bmavity** [comment]
I've been abusing this code pretty heavily over the past couple of weeks and have not seen this crop up. I am going to close this for now, can reopen with code to reproduce if necessary.
