### ISSUE TITLE
error on operations.js no callback

### ISSUE THREAD

**Issue by reharik** [bmavity/ges-client#53]
Hey, sorry for the dumb title can't think of how to say it.
I'm running a test that calls connection.setStreamMetadata. It doesn't assert anything which is why it passes. oh and I have the call to connection.setStreamMetadata in a setTimeout so that the connection can be established before making the call.  Hope this explains the sequence of logs (shown below)
The connection is live as indicated by a console.log (shown below). 
I put a console.log in connectionLogicHandler ln 235.  It says "next" then dumps the next var.
at the end of my console dump below, you'll see the error statement and all the "next"s.
perhaps the best thing is to start below and see the stacktrace and this may make more sense.
Please let me know if there is anything else I can provide.

thanks,
r

next
{ name: 'StartConnection',
  data: { endPoint: { host: '172.17.0.76', port: 1113 } },
  cb: [Function] }
next
{ name: 'StartConnection',
  data: { endPoint: { host: '172.17.0.76', port: 1113 } },
  cb: [Function] }
  appendToStreamPromiseTester
next
{ name: 'EstablishTcpConnection',
  data: { endPoint: { host: '172.17.0.76', port: 1113 } },
  cb: [Function] }
next
{ name: 'EstablishTcpConnection',
  data: { endPoint: { host: '172.17.0.76', port: 1113 } },
  cb: [Function] }
    append to stream
next
{ name: 'TcpConnectionEstablished',
  data: 
   { connection: 
      { domain: null,
        _events: [Object],
        _maxListeners: undefined,
        _socket: [Object],
        _closeCallbacks: [] } } }
next
{ name: 'TcpConnectionEstablished',
  data: 
   { connection: 
      { domain: null,
        _events: [Object],
        _maxListeners: undefined,
        _socket: [Object],
        _closeCallbacks: [] } } }
      ✓ should resolve with success

  1 passing (374ms)

next
{ name: 'HandleTcpPackage',
  data: 
   { connection: 
      { domain: null,
        _events: [Object],
        _maxListeners: undefined,
        _socket: [Object],
        _closeCallbacks: [] },
     package: 
      { messageName: 'HeartbeatRequestCommand',
        flag: 'None',
        correlationId: '73b8a4de-adae-7c47-8160-30ee9bc3ae9d',
        payload: <Buffer > } } }
----------- connection object ----------------
{ domain: null,
  _events: {},
  _maxListeners: undefined,
  _endPoint: { host: '172.17.0.76', port: 1113 },
  _handler: 
   { domain: null,
     _events: { connect: [Function] },
     _maxListeners: undefined,
     _handlers: {},
     _connection: 
      { domain: null,
        _events: [Object],
        _maxListeners: undefined,
        _socket: [Object],
        _closeCallbacks: [] },
     _endPoint: { host: '172.17.0.76', port: 1113 },
     _state: 
      { CloseConnection: [Function: performCloseConnection],
        EstablishTcpConnection: [Function: noOp],
        HandleTcpPackage: [Function: handlePackage],
        StartConnection: [Function],
        StartOperation: [Function],
        StartSubscription: [Function],
        TcpConnectionEstablished: [Function: noOp] },
     _queuedMessages: [],
     _operations: { _activeOperations: {}, _waitingOperations: [] },
     _subscriptions: { _activeSubscriptions: {}, _waitingSubscriptions: [] },
     _connectingPhase: 'Connected' } }
next
{ name: 'StartOperation',
  data: 
   { name: 'AppendToStream',
     stream: '$$$all',
     auth: { username: 'admin', password: 'changeit' },
     data: { expectedVersion: -1, events: [Object] },
     cb: undefined } }
next
{ name: 'HandleTcpPackage',
  data: 
   { connection: 
      { domain: null,
        _events: [Object],
        _maxListeners: undefined,
        _socket: [Object],
        _closeCallbacks: [] },
     package: 
      { messageName: 'HeartbeatRequestCommand',
        flag: 'None',
        correlationId: '63cb297e-5bd9-1449-87b6-b651c74f67af',
        payload: <Buffer > } } }
next
{ name: 'HandleTcpPackage',
  data: 
   { connection: 
      { domain: null,
        _events: [Object],
        _maxListeners: undefined,
        _socket: [Object],
        _closeCallbacks: [] },
     package: 
      { messageName: 'WriteEventsCompleted',
        flag: 'None',
        correlationId: 'a27e6264-d590-485d-8c7e-456c5f132743',
        payload: <Buffer 08 04 12 17 57 72 6f 6e 67 20 65 78 70 65 63 74 65 64 20 76 65 72 73 69 6f 6e 2e 18 80 80 80 80 f8 ff ff ff ff 01 20 80 80 80 80 f8 ff ff ff ff 01 28 ... > } } }
/home/rharik/Development/MethodFitness/mf_workflows/node_modules/eventstore/node_modules/ges-client/tcp/operations.js:52
            return cb(new Error(payload.message))
                   ^
TypeError: undefined is not a function
    at OperationItem.finish (/home/rharik/Development/MethodFitness/mf_workflows/node_modules/eventstore/node_modules/ges-client/tcp/operations.js:52:11)
    at EsConnectionLogicHandler.handlePackage (/home/rharik/Development/MethodFitness/mf_workflows/node_modules/eventstore/node_modules/ges-client/tcp/connectionLogicHandler.js:122:13)
    at EsConnectionLogicHandler._processNextMessage (/home/rharik/Development/MethodFitness/mf_workflows/node_modules/eventstore/node_modules/ges-client/tcp/connectionLogicHandler.js:238:10)
    at Immediate._onImmediate (/home/rharik/Development/MethodFitness/mf_workflows/node_modules/eventstore/node_modules/ges-client/tcp/connectionLogicHandler.js:212:6)
    at processImmediate [as _immediateCallback](timers.js:358:17)

**Comment by reharik** [comment]
wait a minute wait a minute!!!
man took me a while to get through that one. 
freakn setStreamMetadata takes a freakin callback hence if I don't pass one in I'll get a no callback error.  crap!!!!
SORRY
r
